language: julia
os:
  - linux
#  - osx
julia:
  - 0.6.2
#  - nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("ODLCommonTools"); Pkg.test("ODLCommonTools"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("ODLCommonTools")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("ODLCommonTools")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
